# Generated by Django 4.2.17 on 2024-12-31 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=25)),
                ('payment_title', models.CharField(default='Payment', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'CREATED'), ('Pending', 'PENDING'), ('Success', 'SUCCESS'), ('Failed', 'FAILED')], default='Created', max_length=50)),
                ('response_dump', models.JSONField(blank=True, default=dict)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_status', models.CharField(choices=[('Pending', 'PENDING'), ('In Progress', 'IN_PROGRESS'), ('Shipped', 'SHIPPED'), ('Delivered', 'DELIVERED')], default='Pending', max_length=50)),
                ('estimated_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('shipment_address', models.TextField(choices=[('Addis Ababa', 'Addis Ababa'), ('Ērer Sātā', 'Ērer Sātā'), ('Shashemenē', 'Shashemenē'), ('K’ebrī Dehar', 'K’ebrī Dehar'), ('Nazrēt', 'Nazrēt'), ('Mekele', 'Mekele'), ('Godē', 'Godē'), ('Āwasa', 'Āwasa'), ('Dire Dawa', 'Dire Dawa'), ('Bahir Dar', 'Bahir Dar'), ('Sodo', 'Sodo'), ('Ārba Minch’', 'Ārba Minch’'), ('Desē', 'Desē'), ('Hosa’ina', 'Hosa’ina'), ('K’ebrī Beyah', 'K’ebrī Beyah'), ('Jijiga', 'Jijiga'), ('Dīla', 'Dīla'), ('Nek’emtē', 'Nek’emtē'), ('Debre Birhan', 'Debre Birhan'), ('Debre Mark’os', 'Debre Mark’os'), ('Ferfer', 'Ferfer'), ('Āwarē', 'Āwarē'), ('Harar', 'Harar'), ('Kombolcha', 'Kombolcha'), ('Jīma', 'Jīma'), ('Debre Tabor', 'Debre Tabor'), ('Harshin', 'Harshin'), ('Ādīgrat', 'Ādīgrat'), ('Debre Zeyit', 'Debre Zeyit'), ('Gambēla', 'Gambēla'), ('Mīzan Teferī', 'Mīzan Teferī'), ('Ādwa', 'Ādwa'), ('Gonder', 'Gonder'), ('Bodītī', 'Bodītī'), ('Āsela', 'Āsela'), ('Āksum', 'Āksum'), ('Bonga', 'Bonga'), ('Finote Selam', 'Finote Selam'), ('Semera', 'Semera'), ('Goba', 'Goba'), ('Hāgere Hiywet', 'Hāgere Hiywet'), ('Robē', 'Robē'), ('Yirga ‘Alem', 'Yirga ‘Alem'), ('Giyon', 'Giyon'), ('Bedēsa', 'Bedēsa'), ('Āzezo', 'Āzezo'), ('Butajīra', 'Butajīra'), ('Ālamat’ā', 'Ālamat’ā'), ('Āreka', 'Āreka'), ('Gīmbī', 'Gīmbī'), ('Wik’ro', 'Wik’ro'), ('Welk’īt’ē', 'Welk’īt’ē'), ('Metu', 'Metu'), ('Fichē', 'Fichē'), ('K’olīto', 'K’olīto'), ('Genet', 'Genet'), ('Āgaro', 'Āgaro'), ('Gelemso', 'Gelemso'), ('Āsosa', 'Āsosa')])),
                ('shipment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.PositiveIntegerField()),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
