# Generated by Django 4.2.17 on 2025-01-02 22:27

from django.db import migrations


def create_default_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="admin")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_shipment_shipment_status"),
    ]

    operations = [migrations.RunPython(create_default_group)]
