# Generated by Django 4.2.17 on 2025-01-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_default_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='item_count',
            field=models.PositiveIntegerField(verbose_name='Number of units'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
    ]
